project:
  type: website
  output-dir: docs

website:
  title: "Microbial Genomics Lab"
  navbar:
    background: primary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    embed-resources: true